name: granule
version: '0.3.9.0'
synopsis: The Granule type checker and interpreter
author: Dominic Orchard
copyright: 2017 authors
license: BSD3
github: dorchard/granule
extra-source-files:
- README.md
- LICENSE
dependencies:
- base >=4.10 && <5

library:
  source-dirs: source
  ghc-options: -Wall -fno-warn-name-shadowing
  build-tools:
  - alex
  - happy
  exposed-modules:
  - Checker.Checker
  - Checker.Coeffects
  - Checker.Constraints
  - Checker.Kinds
  - Checker.LaTeX
  - Checker.Monad
  - Checker.Patterns
  - Checker.Predicates
  - Checker.Primitives
  - Checker.Types
  - Context
  - Eval
  - Syntax.Desugar
  - Syntax.Expr
  - Syntax.FirstParameter
  - Syntax.Lexer
  - Syntax.Parser
  - Syntax.Pretty
  - Utils
  dependencies:
  - array
  - containers
  - mtl >=2.2.1
  - sbv >=7.3
  - transformers >=0.5

executables:
  gr:
    main: Main.hs
    source-dirs: command-line-interface
    dependencies:
    - Glob
    - granule
    - optparse-applicative

tests:
  spec:
    main: Spec.hs
    source-dirs: tests/hspec
    ghc-options: -fno-warn-partial-type-signatures
    dependencies:
    - filemanip
    - granule
    - hspec
    - QuickCheck
    - mtl
    - transformers >=0.5
  zdoctest: # the "z" is to make them run after hspec
    main: doctest.hs
    source-dirs: tests
    dependencies:
    - doctest
    ghc-options: -threaded
