name: granule
version: '0.5.0.1'
synopsis: The Granule type checker and interpreter
author: Dominic Orchard, Vilem-Benjamin Liepelt
copyright: 2018 authors
license: BSD3
github: dorchard/granule
extra-source-files:
- README.md
- LICENSE
dependencies:
- base >=4.10 && <5

library:
  source-dirs: source
  ghc-options: -O0 -W -Werror -Wno-unused-matches -Wwarn=incomplete-patterns
  # when:
  # - condition: flag(dev)
  #   then:
  #     ghc-options: -O0 -W -Werror -Wno-unused-matches
  #   else:
  #     ghc-options: -O3 -w
  build-tools:
  - alex
  - happy
  exposed-modules:
  - Checker.Checker
  - Checker.Coeffects
  - Checker.Constraints
  - Checker.Kinds
  - Checker.LaTeX
  - Checker.Monad
  - Checker.Patterns
  - Checker.Predicates
  - Checker.Primitives
  - Checker.Substitutions
  - Checker.Types
  - Context
  - Eval
  - Syntax.Desugar
  - Syntax.Expr
  - Syntax.FirstParameter
  - Syntax.Lexer
  - Syntax.Parser
  - Syntax.Pretty
  - Utils
  - Repl.Repl
  - Repl.Queue
  dependencies:
  - array
  - containers
  - mtl >=2.2.1
  - sbv >=7.3
  - time
  - transformers >=0.5
  - haskeline

executables:
  gr:
    main: Main.hs
    source-dirs: command-line-interface
    ghc-options: -O0 -W -Werror -Wno-unused-matches
    dependencies:
    - Glob
    - granule
    - optparse-applicative

# flags:
#   dev:
#     default: True
#     manual: True

tests:
  spec:
    main: Spec.hs
    source-dirs: tests/hspec
    ghc-options: -fno-warn-partial-type-signatures
    dependencies:
    - filemanip
    - granule
    - hspec
    - QuickCheck
    - mtl
    - transformers >=0.5
  zdoctest: # the "z" is to make them run after hspec
    main: doctest.hs
    source-dirs: tests
    dependencies:
    - doctest
    - granule
    ghc-options: -threaded
