name: granule-repl
version: '0.6.0.4'
synopsis: The GRanule INteractive interpreter
author: Dominic Orchard, Vilem-Benjamin Liepelt, Harley Eades III, Preston Keel
copyright: 2018 authors
license: BSD3
github: dorchard/granule
dependencies:
- base >=4.10 && <5

executables:
  grin:
    main: Main.hs
    source-dirs: app
    ghc-options: -O3 -W -Werror -Wno-unused-matches
    # exposed-modules:
    # - Queue
    # - ReplError
    # - ReplParser
    dependencies:
    - granule-interpreter
    - granule-frontend
    - ConfigFile
    - containers
    - Glob
    - directory
    - filemanip
    - filepath
    - haskeline
    - mtl >=2.2.1
    - parsec
    - text
    - transformers >=0.5
